# Generated by Django 5.2 on 2025-06-29 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_core', '0004_comment_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='content_id',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='member_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lms_core.coursecontent'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms_core.coursemember'),
        ),
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='komentar'),
        ),
    ]
