# Generated by Django 5.2 on 2025-06-29 19:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_core', '0005_remove_comment_comment_remove_comment_content_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='available_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tayang Mulai'),
        ),
    ]
