# Generated by Django 5.2 on 2025-06-29 19:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_core', '0006_comment_available_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecontent',
            name='available_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tayang Mulai'),
        ),
    ]
