# Generated by Django 5.2 on 2025-06-29 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_core', '0007_coursecontent_available_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='max_students',
            field=models.IntegerField(default=100, verbose_name='Maksimal Siswa'),
        ),
    ]
