# Generated by Django 5.2 on 2025-06-29 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_core', '0008_course_max_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemember',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
