# Generated by Django 5.2 on 2025-06-29 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_core', '0010_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_core.coursecontent')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_core.coursemember')),
            ],
            options={
                'unique_together': {('member', 'content')},
            },
        ),
    ]
